# Render.com Deployment Configuration

# Static Site Settings
build: yarn build
buildCommand: yarn build
publishDir: build
env: production

# Build Environment
NODE_VERSION: 18
YARN_VERSION: 1.22.22
NODE_ENV: production

# Build optimization
GENERATE_SOURCEMAP: false
CI: true